### ISSUE TITLE
Any example?

### ISSUE THREAD

**Issue by samuelpatro** [AlexandreBonaventure/vuex-jsdata-plugin#1]
Hey, i like to use this plugin, but i don't know how to integrade with actions, mutations in Vuex. Can you please provide some examples?

**Comment by AlexandreBonaventure** [comment]
Sure, I've uploaded an example.
Just download the repo and run 
```
npm install
npm run example-simple
```

**Comment by AlexandreBonaventure** [comment]
You can take a look in here : 
https://github.com/AlexandreBonaventure/vuex-jsdata-plugin/tree/master/examples/simple
😄

**Comment by samuelpatro** [comment]
Thanks, do you thinking about updating js-data to v3? And why is in main package used Vue 1? but Vuex is on 2?

**Comment by AlexandreBonaventure** [comment]
Yes, supporting js-datav3 is planned but it's still in beta.
Vuex isn't tied with Vue 2.x; Its working along Vue 1.x seamlessly.
This plugin was built for application purpose working with Vue 1.x, so that's why support for Vue 2.x isn't guaranteed for now (but would be).

This is my first open-source code maintenance experience so I'll try to do my best.
Thanks for your interest.

**Comment by samuelpatro** [comment]
On js-data github is
https://github.com/js-data/js-data/tree/master
> JSData v3 release candidate is stable. More features may be added before 3.0.0, and there might be some bugs. Some adapters still need to be updated to work with v3. Message @jmdobry on the JSData Slack channel if you want to help with tests, documentation, tutorials, adapters, etc.

I ask about that Vue because 1 day ago was release Vuex 2.1 with pretty cool features. -- I test it and its working with Vue 2 too :-)

Thanks for your feedback 👍

**Comment by samuelpatro** [comment]
Any update?

**Comment by AlexandreBonaventure** [comment]
I updated the example to work with vue 2.0 and seems compatible. Have a look.
Despite js-data 3.0RC is stable, it lacks of documentation and I don't have much time to investigate.
I'm closing this for now, till js-data 3.0 is released with a full documentation.
