### ISSUE TITLE
Object.value it's not supported on electron

### ISSUE THREAD

**Issue by kurtulik** [AlexandreBonaventure/vuex-jsdata-plugin#2]
I replace this line and it's working
`var ressources = Object.values(DStore.definitions);`
replace by:
`var ressources = Object.keys(DStore.definitions).map(key => DStore.definitions[key])`

in js-data store is not supported registerModel function  `store.registerModel('User', User) `

```
// Register a model in js-data

export const User = store.defineResource({
  name: 'user',
  endpoint: 'users',
})

store.registerModel('User', User)
export default User
```

**Comment by AlexandreBonaventure** [comment]
Thanks for filing the issue. I polyfilled the method. Will be available in 0.2.0
ps: thanks also for the readme I fixed it ! (oups)
